const RECEIVE_PEACE = "RECEIVE_PEACE";
const UPDATE_PIECE = "UPDATE_PIECE";
const UPDATE_FAILURE = "UPDATE_FAILURE";
const INITIALIZE_REQUEST = "INITIALIZE_REQUEST";
const INITIALIZE_SUCCESS = "INITIALIZE_SUCCESS";
const INITIALIZE_FAILURE = "INITIALIZE_FAILURE";

export default { RECEIVE_PEACE, UPDATE_PIECE, UPDATE_FAILURE, INITIALIZE_REQUEST, INITIALIZE_SUCCESS, INITIALIZE_FAILURE };
